### ISSUE TITLE
Tracking Needed Pre-Release Changes

### ISSUE THREAD

**Issue by MrCryptoT** [mwcproject/docs#14]
Tracking needed Pre-Release changes to Docs here: 
All steps mentioned are required "Pre-Release" unless marked with *

- [x] Make sure the new "Switch Instances" Version is up to date.

- [x] Switch out the "Switch Instances" Links with new version (Getstarted and in Sidebar) 

- [x] Create new Category in _Sidebar for Cold Wallet Guides (see below) 
This is out of Date, we agreed on maintaining the 1 Cold wallet guide as a master that links further

- [x] Inlcude new Cold Storage Guides in new Cat (Getstarted and in Sidebar) 
https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/cold_wallet_software_installation_guide.md
https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/cold_wallet_persistent_usb_drive_creation.md
This is out of Date, we agreed on maintaining the 1 Cold wallet guide as a master that links further

- [x] Double Check that the Send/Receive Guides for Cold Wallets are still valid

- [x] Make sure https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/cold_wallet.md is still up to date and not duplicated or deprecated
Scassallet did a great job of updating the cold wallet guides so this is ensured. 

- [x] Create a Docs about Swaps-feature in the QT

- [x] *Create a Video about Swaps-feature in the QT (Make sure we can integrate the Video well in the Wiki) 

- [x] *Think about what to do with Swap-feature Docs for the CLI (As they are rather advanced - maybe we shouldn't link that one ) <br> Conclusion: Don't link it in Sidebar for now.

- [x] Link to new Notification Windows Doc (Getstarted and in Sidebar) see  #16 

- [x] Remove link to "Claim HODL Rewards" as it's deprecated

- [x] Rename "Manage Funds" to Category name agreed upon in Isssue 16

- [x] Link Atomic Swaps docs in wiki when released

- [ ] Add "Change Fees" Section to Swaps Wiki page

- [ ] Add "Check swap status" Section to Swaps Wiki page

**Comment by MrCryptoT** [comment]
Actually need to followup on the cold wallet guides, from memory I think we agreed to keep 1 master docs but there was a side disscussion about old cli/qt cold storage link on the webpage in a footer section (which is not grabbing links from the sidebar unlike the /docs page)

**Comment by MrCryptoT** [comment]
Yeah did re-read old Convos, All that's needed now is doublechecking all additions and changes, grammar and spelling, and the video about Swaps.

**Comment by MrCryptoT** [comment]
Im thinking of waiting with the Change fees/Check Status Sections in the guide until Release. (to see if even needed) 
The UI is pretty self explanatory. 
Once an OOTB Release including Swaps is released I will be ready on Stand by for User Support.
I'll close this Issue for now as technically all required Changes to Documentation is done including a Video explaining the Swap process.
